"""drop group leader fk

Revision ID: 9b5fc647a868
Revises: 982684282f94
Create Date: 2026-03-20 12:42:42.662277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b5fc647a868'
down_revision: Union[str, None] = '982684282f94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

FK_NAMING_CONVENTION = {
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
}
LEADER_FK_NAME = "fk_student_groups_leader_student_id_students"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = sa.inspect(op.get_bind())
    foreign_keys = inspector.get_foreign_keys('student_groups')
    foreign_key_names = {foreign_key.get('name') for foreign_key in foreign_keys}

    if LEADER_FK_NAME in foreign_key_names:
        with op.batch_alter_table(
            'student_groups',
            schema=None,
            naming_convention=FK_NAMING_CONVENTION,
        ) as batch_op:
            batch_op.drop_constraint(LEADER_FK_NAME, type_='foreignkey')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_groups', schema=None) as batch_op:
        batch_op.create_foreign_key(
            LEADER_FK_NAME,
            'students',
            ['leader_student_id'],
            ['id'],
        )

    # ### end Alembic commands ###
